#spring.application.name=yoshlar_tashabusi_app
#server.port=7777
#spring.sql.init.platform=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/yoshlar_tashabusi_app_db
#spring.datasource.username=postgres
#spring.datasource.password=root123
#spring.jpa.hibernate.ddl-auto=create


spring.application.name=yoshlar_tashabusi_app
server.port=7777

# Bu qator ko'pincha shart emas, Spring avtomatik aniqlaydi
# spring.sql.init.platform=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/yoshlar_tashabusi_app_db
spring.datasource.username=postgres
spring.datasource.password=root123

# Hibernate sozlamalari
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true